<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LapanganSeeder extends Seeder
{
    public function run(): void
    {
        $lapangans = [
            [
                'name'         => 'KickIn Standard',
                'type'         => 'indoor',
                'description'  => 'Lantai rubber anti-slip, pencahayaan LED merata, ruang ganti bersih, lokasi strategis di pusat kota.',
                'price_1jam'   => null,
                'price_2jam'   => 120000,
                'price_3jam'   => 170000,
                'price_4jam'   => 220000,
                'price_5jam'   => 260000,
                'price_6jam'   => null,
                'opening_time' => '07:00',
                'closing_time' => '23:00',
                'is_active'    => true,
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'name'         => 'KickIn Premium',
                'type'         => 'indoor',
                'description'  => 'Lantai rubber empuk (nyaman untuk lutut), AC, WiFi, mushola, lounge, minuman gratis.',
                'price_1jam'   => null,
                'price_2jam'   => 180000,
                'price_3jam'   => 260000,
                'price_4jam'   => 330000,
                'price_5jam'   => 390000,
                'price_6jam'   => null,
                'opening_time' => '07:00',
                'closing_time' => '23:00',
                'is_active'    => true,
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'name'         => 'KickIn Outdoor',
                'type'         => 'outdoor',
                'description'  => 'Rumput sintetis tebal dengan filler karet, lampu sorot LED, tribun, parkir luas, cocok latihan tim.',
                'price_1jam'   => null,
                'price_2jam'   => 100000,
                'price_3jam'   => 145000,
                'price_4jam'   => 185000,
                'price_5jam'   => 220000,
                'price_6jam'   => null,
                'opening_time' => '07:00',
                'closing_time' => '23:00',
                'is_active'    => true,
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'name'         => 'KickIn Pro Arena',
                'type'         => 'indoor',
                'description'  => 'Lantai rubber grade turnamen, papan skor digital, ruang ganti eksklusif, kamar mandi shower.',
                'price_1jam'   => null,
                'price_2jam'   => 220000,
                'price_3jam'   => 310000,
                'price_4jam'   => 400000,
                'price_5jam'   => 480000,
                'price_6jam'   => null,
                'opening_time' => '07:00',
                'closing_time' => '23:00',
                'is_active'    => true,
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'name'         => 'KickIn Mini Soccer',
                'type'         => 'outdoor',
                'description'  => 'Lapangan ukuran 3vs3/4vs4, rumput sintetis pendek, jaring pengaman, cocok anak & pemula.',
                'price_1jam'   => null,
                'price_2jam'   => 80000,
                'price_3jam'   => 115000,
                'price_4jam'   => 145000,
                'price_5jam'   => 170000,
                'price_6jam'   => null,
                'opening_time' => '07:00',
                'closing_time' => '23:00',
                'is_active'    => true,
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'name'         => 'KickIn Executive',
                'type'         => 'indoor',
                'description'  => 'Lantai rubber premium + peredam benturan, ruang ganti mewah (shower, loker), lounge VIP.',
                'price_1jam'   => null,
                'price_2jam'   => 250000,
                'price_3jam'   => 360000,
                'price_4jam'   => 460000,
                'price_5jam'   => 550000,
                'price_6jam'   => null,
                'opening_time' => '07:00',
                'closing_time' => '23:00',
                'is_active'    => true,
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'name'         => 'KickIn Green Field',
                'type'         => 'outdoor',
                'description'  => 'Rumput sintetis hijau natural, sistem drainase cepat, pencahayaan 360°, area teduh.',
                'price_1jam'   => null,
                'price_2jam'   => 110000,
                'price_3jam'   => 160000,
                'price_4jam'   => 205000,
                'price_5jam'   => 245000,
                'price_6jam'   => null,
                'opening_time' => '07:00',
                'closing_time' => '23:00',
                'is_active'    => true,
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
        ];

        DB::table('lapangans')->insert($lapangans);
    }
}